<?php

namespace WorldBundle\Repository;

/**
 * NationsInCountriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationsInCountriesRepository extends \Doctrine\ORM\EntityRepository
{
}
